[build]
  base = "/"
  publish = "storybook-static/"
  command = "yarn build-storybook"
  # shell exit $? = 0 to early return, thus ignore the build
  ignore = "git log -1 --pretty=%B"

[context.deploy-preview]
  # ignore building PR deploy previews with commit that doesn't have "[build]" in commit messages
  ignore = "./netlify-dp-ignore.sh"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
